Feature issue#5
ISPP-2023-NGO-P3/backend-aiding pull request #16
Opened 2023-03-08 23:49 UTC by aisqazcev

_total_donation_ simplificado, ya no es un atributo, por tanto tampoco existen las donaciones puntuales, habría que darle una vuelta  si se quieren hacer

2023-03-09 21:22 UTC, Rick3600 requested changes
Faltan realizar los nuevos cambios aclarados por el cliente

2023-03-10 17:22 UTC, aisqazcev commented
> Faltan realizar los nuevos cambios aclarados por el cliente

Los cambios son varios, así que no serán para este sprint, se queda con una donación simplificada.

2023-03-11 11:40 UTC, Rick3600 approved these changes

2023-03-11 14:44 UTC, Rick3600 requested changes
Falta arreglar los fallos medios y superiores de codacy, aunque si es posible arregla los pequeños también

2023-03-12 12:41 UTC, Rick3600 requested changes
Al crear un partner sale este error, cosa que antes no ocurría
![image](https://user-images.githubusercontent.com/72402373/224545280-6e8917dd-5f50-4755-aa1c-1591a5aab051.png)

2023-03-12 13:06 UTC, Rick3600 approved these changes

2023-03-12 13:06 UTC, Rick3600 commented
Todo funciona correctamente

2023-03-12 13:33 UTC, Rick3600 commented
Todo funciona correctamente

2023-03-12 13:36 UTC, merged