Feature issue#12
ISPP-2023-NGO-P3/backend-aiding pull request #18
Opened 2023-03-09 14:27 UTC by marolmmar1

2023-03-09 14:42 UTC, Rick3600 requested changes
Las urls deberian seguir el esquema de partner_id/communication/comunication_id al ser las comunicaciones dependientes de los partners

2023-03-09 20:57 UTC, marolmmar1 commented
He actualizado las urls y mejorado la API

2023-03-09 21:14 UTC, marolmmar1 commented
Completado, sin bad smells

2023-03-09 21:24 UTC, Rick3600 requested changes
Por favor no subas archivos que no hayas modificado realmente como el de base/models.py o las migraciones

2023-03-09 21:25 UTC, Rick3600 commented
Por favor no subas archivos que realmente no hayas modificado como el de base/models o

2023-03-09 21:59 UTC, Rick3600 requested changes
Pon los enumerates en ingles para seguir el esquema general

2023-03-09 22:06 UTC, Rick3600 requested changes
Falta realizar el código para tener una pagina de admin, para poder hacer crud manual de lo nuevo añadido

2023-03-10 09:20 UTC, marolmmar1 commented
Traducido el enumerado y añadido el código de admins

2023-03-11 09:55 UTC, Rick3600 approved these changes

2023-03-11 09:57 UTC, Rick3600 requested changes
Cambia el get() a esta forma ya que actualmente no funciona 
![Captura_de_pantalla_2023-03-11_105532](https://user-images.githubusercontent.com/72402373/224477801-3bf82432-2dc6-4020-809b-03b4cca50318.png)


![image](https://user-images.githubusercontent.com/72402373/224477745-5f07a932-fc60-483c-a728-c113239e1ddc.png)

2023-03-12 19:26 UTC, Rick3600 approved these changes

2023-03-12 19:26 UTC, merged