Feature issue#64
ISPP-2023-NGO-P3/backend-aiding pull request #86
Opened 2023-04-22 16:27 UTC by nicsanmen

2023-04-24 16:02 UTC, mansanrod4 requested changes

2023-04-24 16:02 UTC, mansanrod4 commented on aiding/base/views.py
> +                    print("contraseña del usuario: ", user.password)
Faltan estos prints por borrar, además no se si es conveniente que devolvamos la contraseña. No debería ser que al poner la contraseña antigua bien deje cambiarla?

2023-04-24 16:55 UTC, cardelbec approved these changes
Lo veo todo bien, cambiad lo que os ha puesto manu en el comentario y lo mergeamos

2023-04-25 08:47 UTC, nicsanmen commented on aiding/base/views.py
> +                    print("contraseña del usuario: ", user.password)
no entiendo a lo que te refieres con lo de que devolvamos la contraseña. Los prints sí se me pasaron, cuando me aclare lo 2º que me has dicho veo si hay que cambiar algo más y hago pr sin los prints también

2023-04-25 15:44 UTC, mansanrod4 commented on aiding/base/views.py
> +                    print("contraseña del usuario: ", user.password)
Nada,  entiendo que es para que el administrador pueda cambiar todas las cuentas de usuario. Quitando los prints está bien.

2023-04-25 16:04 UTC, mansanrod4 approved these changes

2023-04-25 16:05 UTC, merged